on:
  workflow_run:
    workflows: [Release NPM]
    types:
      - completed

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    
      # checkout branch 2.6
      - name: Checkout branch 2.7
        uses: actions/checkout@v2
        with: 
          ref: '2.7'

      - run: yarn --frozen-lockfile

      - name: Bootstrap platform
        run: |
          yarn bootstrap

      - name: Sync cnpm
        env:
          CI: true
        run: |
          yarn sync

